// netlify/functions/view-report.js
//
// Serves a previously saved report by ID. Reached via the redirect rule
// /r/:id -> /.netlify/functions/view-report?id=:id (add to netlify.toml,
// see instructions).

const { getConfiguredStore } = require('./_blobs-config');

function safeReportId(value) {
  const id = String(value || '').trim();
  // Report keys are generated by this site (UUIDs, with a legacy
  // date-and-random fallback). Reject path traversal and arbitrary blob keys.
  return /^[A-Za-z0-9][A-Za-z0-9-]{0,127}$/.test(id) ? id : null;
}

function decodedSegment(value) {
  try { return decodeURIComponent(String(value || '')); }
  catch { return null; }
}

function reportIdFromPath(path) {
  const pathname = String(path || '').split('?')[0];
  const parts = pathname.split('/').filter(Boolean);
  // Covers both the original short URL (/r/:id) and the internal function
  // rewrite (/.netlify/functions/view-report/:id).
  for (const marker of ['view-report', 'r']) {
    const index = parts.lastIndexOf(marker);
    if (index >= 0 && parts[index + 1]) return safeReportId(decodedSegment(parts[index + 1]));
  }
  return null;
}

function getReportId(event = {}) {
  const queryId = event.queryStringParameters && event.queryStringParameters.id;
  const directId = safeReportId(queryId);
  if (directId) return directId;

  const pathParameterId = safeReportId(event.pathParameters && (event.pathParameters.id || event.pathParameters.splat));
  if (pathParameterId) return pathParameterId;

  return reportIdFromPath(event.path) || reportIdFromPath(event.rawUrl);
}

exports.handler = async (event) => {
  const id = getReportId(event);

  if (!id) {
    return { statusCode: 400, headers: { "Content-Type": "text/plain" }, body: "Missing report id" };
  }

  try {
    const reportsStore = getConfiguredStore("reports");
    const html = await reportsStore.get(id, { type: "text" });

    if (!html) {
      return {
        statusCode: 404,
        headers: { "Content-Type": "text/html" },
        body: "<h1>Report not found</h1><p>This link may have expired or the report ID is incorrect.</p>"
      };
    }

    return {
      statusCode: 200,
      headers: { "Content-Type": "text/html; charset=utf-8" },
      body: html
    };
  } catch (err) {
    return {
      statusCode: 500,
      headers: { "Content-Type": "text/plain" },
      body: "Failed to load report: " + String(err).slice(0, 300)
    };
  }
};
